name: Daily Stock Data Update

on:
  schedule:
    # التحديث يومياً الساعة 4 مساءً بتوقيت الإمارات (UTC+4)
    # UTC time: 12:00 (noon)
    - cron: '0 12 * * *'
  workflow_dispatch: # السماح بالتشغيل اليدوي

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r scripts/requirements.txt
        
    - name: Create data directory
      run: mkdir -p data historical_data
      
    - name: Run data scraper
      run: python scripts/scraper.py
      
    - name: Update HTML pages
      run: python scripts/update_html.py
      
    - name: Archive historical data
      run: |
        # إنشاء ملف تاريخي باسم التاريخ
        cp data/daily_data.json "data/historical_data/$(date +%Y-%m-%d).json"
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff --staged --quiet || git commit -m "Daily stock data update - $(date '+%Y-%m-%d %H:%M:%S')"
        git push
